//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelChatbotDesarrollo.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int MensajeId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Origen { get; set; }
        public int Estado { get; set; }
        public string Mensaje { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
