//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelChatbotDesarrollo.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Chatbot_DesarrolloEntities : DbContext
    {
        public Chatbot_DesarrolloEntities()
            : base("name=Chatbot_DesarrolloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<Mensajes> Mensajes { get; set; }
        public virtual DbSet<Negocios> Negocios { get; set; }
        public virtual DbSet<Rubros> Rubros { get; set; }
        public virtual DbSet<SubRubros> SubRubros { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<UsuarioProveedor> UsuarioProveedor { get; set; }
        public virtual DbSet<NegocioAuthentication> NegocioAuthentication { get; set; }
    }
}
