//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelChatbotDesarrollo.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class NegocioAuthentication
    {
        public string SecretId { get; set; }
        public string Code { get; set; }
        public string Authentication { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual Negocios Negocios { get; set; }
    }
}
