//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelChatbotDesarrollo.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsCodes
    {
        public int SmsCodeId { get; set; }
        public string Telefono { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaVence { get; set; }
        public Nullable<System.DateTime> FechaUso { get; set; }
        public int Intentos { get; set; }
    }
}
