//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelChatbotDesarrollo.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioProveedor
    {
        public int UsuarioId { get; set; }
        public int ProveedorId { get; set; }
        public string UsuarioProveedorId { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
